### ISSUE TITLE
'attempt to subtract with overflow', console/console-subscriber/src/aggregator/mod.rs:252:9

### ISSUE THREAD

**Issue by pymongo** [tokio-rs/console#242]
## console_subscriber version:
```
commit ef5530311a7cc841c7b8fab3ca04711872943f3e (HEAD -> main, origin/main, origin/HEAD)
Author: Eliza Weisman <eliza@buoyant.io>
Date:   Thu Dec 23 14:32:51 2021 -0800
```

## backtrace
```
Dec 24 16:24:31 ww atlasd[590091]: thread 'console_subscriber' panicked at 'attempt to subtract with overflow', /home/w/repos/clone_repos/console/console-subscriber/src/aggregator/mod.rs:25>
Dec 24 16:24:31 ww atlasd[590091]: stack backtrace:
Dec 24 16:24:31 ww atlasd[590091]:    0: rust_begin_unwind
Dec 24 16:24:31 ww atlasd[590091]:              at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
Dec 24 16:24:31 ww atlasd[590091]:    1: core::panicking::panic_fmt
Dec 24 16:24:31 ww atlasd[590091]:              at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
Dec 24 16:24:31 ww atlasd[590091]:    2: core::panicking::panic
Dec 24 16:24:31 ww atlasd[590091]:              at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
Dec 24 16:24:31 ww atlasd[590091]:    3: console_subscriber::aggregator::PollStats::update_on_span_exit
Dec 24 16:24:31 ww atlasd[590091]:              at /home/w/repos/clone_repos/console/console-subscriber/src/aggregator/mod.rs:252:9
Dec 24 16:24:31 ww atlasd[590091]:    4: console_subscriber::aggregator::Aggregator::update_state
Dec 24 16:24:31 ww atlasd[590091]:              at /home/w/repos/clone_repos/console/console-subscriber/src/aggregator/mod.rs:641:21
Dec 24 16:24:31 ww atlasd[590091]:    5: console_subscriber::aggregator::Aggregator::run::{{closure}}
Dec 24 16:24:31 ww atlasd[590091]:              at /home/w/repos/clone_repos/console/console-subscriber/src/aggregator/mod.rs:380:25
Dec 24 16:24:31 ww atlasd[590091]:    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
```

**Comment by hawkw** [comment]
I believe #238 fixes this issue. Are you able to try the latest git revision of `console-subscriber` (fdc77e28d45da73595320fab8ce56f982c562bb6) and confirm that this is the case? You'll also need to build the git version of the console CLI.

**Comment by hawkw** [comment]
quick ping @pymongo — can you confirm that #238 fixes this issue?
